name: Daily Motivation

on:
  schedule:
    - cron: "30 2 * * *" # Runs daily at 8:00 AM IST
  workflow_dispatch: # Allow manual trigger

jobs:
  send-motivation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run motivation script
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TO_NUMBER: ${{ secrets.TO_NUMBER }}
        run: python ocr_calendar.py
